# Generated by Django 4.2.23 on 2025-08-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WledInstance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wled_id",
                    models.PositiveIntegerField(unique=True, verbose_name="WLED ID"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP Address")),
                (
                    "max_leds",
                    models.PositiveIntegerField(default=1, verbose_name="Max LEDs"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "WLED Instance",
                "verbose_name_plural": "WLED Instances",
                "ordering": ["wled_id"],
            },
        ),
    ]
